### ISSUE TITLE
Running import script gets many varchar(255) errors.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/smoke-alarm-portal#62]
I first encountered this on the `58_email_sending` branch, but have since confirmed that it happens on `master` as well.  Note that the db works after this import, even with the errors.  `npm start` works, and the application works, it's just that seeing those errors in the import step makes me wonder if some counties/regions/whatever might give falsely negative results if I happened to hit them.

    $ node data/import_into_postgres.js 
    County [object SequelizeInstance:SelectedCounties] added
    County [object SequelizeInstance:SelectedCounties] added
    County [object SequelizeInstance:SelectedCounties] added
    County [object SequelizeInstance:SelectedCounties] added
    County [object SequelizeInstance:SelectedCounties] added
    <... a lot of this, and then...>
    Unhandled rejection SequelizeDatabaseError: value too long for type character varying(255)
        at Query.formatError (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
        at null.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
        at emit (events.js:95:17)
        at Query.handleError (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/query.js:99:8)
        at null.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/client.js:166:26)
        at emit (events.js:95:17)
        at Socket.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/connection.js:109:12)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:765:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
        at readableAddChunk (_stream_readable.js:166:9)
        at Socket.Readable.push (_stream_readable.js:128:10)
        at TCP.onread (net.js:529:21)
    County [object SequelizeInstance:SelectedCounties] added
    Address [object SequelizeInstance:UsAddress] added
    Address [object SequelizeInstance:UsAddress] added
    Address [object SequelizeInstance:UsAddress] added
    Address [object SequelizeInstance:UsAddress] added
    Address [object SequelizeInstance:UsAddress] added
    Address [object SequelizeInstance:UsAddress] added
    Unhandled rejection SequelizeDatabaseError: value too long for type character varying(255)
        at Query.formatError (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
        at null.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
        at emit (events.js:95:17)
        at Query.handleError (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/query.js:99:8)
        at null.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/client.js:166:26)
        at emit (events.js:95:17)
        at Socket.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/connection.js:109:12)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:765:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
        at readableAddChunk (_stream_readable.js:166:9)
        at Socket.Readable.push (_stream_readable.js:128:10)
        at TCP.onread (net.js:529:21)
    Address [object SequelizeInstance:UsAddress] added
    Address [object SequelizeInstance:UsAddress] added
    Unhandled rejection SequelizeDatabaseError: value too long for type character varying(255)
        at Query.formatError (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
        at null.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
        at emit (events.js:95:17)
        at Query.handleError (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/query.js:99:8)
        at null.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/client.js:166:26)
        at emit (events.js:95:17)
        at Socket.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/connection.js:109:12)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:765:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
        at readableAddChunk (_stream_readable.js:166:9)
        at Socket.Readable.push (_stream_readable.js:128:10)
        at TCP.onread (net.js:529:21)
    <... lots more such errors as the output continues...>

**Comment by kfogel** [comment]
Okay, I see what this probably is now: in `data/us_addresses.json`, the "acceptable_cities" and "unacceptable_cities" fields often run over 255 characters, because the value string can be an arbitrarily long comma-separated list of cities.

Created branch `62_varchar_length_fixes`, and commit 024f8c2380e on that branch already fixes this bug.  However, there's a cleaner and more general fix; watch this space for more.

**Comment by kfogel** [comment]
Yup.  Commit 6af3ec9789c, also on the `62_varchar_length_fixes` branch, is the clean way to solve this.

Leaving this ticket open until these changes land on trunk.
